### ISSUE TITLE
Authentication failure (send_and_respond return empty response)

### ISSUE THREAD

**Issue by ditatompel** [bentasker/telegraf-plugins#1]
Hi, first of all, thank you for sharing your scripts!

I have a problem when running the Tor Daemon Plugin. This is the output when I run the script.
```
tor,controlport_connection=failed,failure_type=authentication stats_fetch_failures=1i
```
Python Version `3.10.5`
Tor Version:
```
Tor version 0.4.7.7.
Tor is running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1o, Zlib 1.2.12, Liblzma 5.2.5, Libzstd 1.5.2 and Glibc 2.35 as libc.
Tor compiled with GCC version 12.1.0
```

Note:
1. I'm able to connect to ControlPort using telnet.
```
telnet 127.0.0.1 9051
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
AUTHENTICATE "my auth pass"
250 OK
getinfo traffic/read
250-traffic/read=15697
250 OK
quit
250 closing connection
Connection closed by foreign host.
```

2. When I try to run the script, it can connect to ControlPort (journalctl -f shows: `Jun 14 14:02:20 myhostname Tor[58134]: New control connection opened from 127.0.0.1`.
3. But fail to receive (or maybe parse) response when sending `AUTHENTICATE` command from Control Port (tried to add `print(sock.recv(1024)` on [line 49](https://github.com/bentasker/telegraf-plugins/blob/master/tor-daemon/tor-daemon.py#L49) for debugging purpose) 

Any idea how to I fix this on my machine or clue for debugging purpose?

Thanks

**Comment by bentasker** [comment]
It might be worth running a packet capture to see what's hitting the wire.

If you do
```
tcpdump -i lo -s0 -w controlport.pcap -v port 9051
```

and then wait for the plugin to fire (or trigger it yourself) you should see the packet counter in tcpdump increment.

You can then view the capture in wireshark or with
```
tcpdump -r controlport.pcap -X
```

to see what's being sent.

To get that error back you're [either getting a short response or a non 250](https://github.com/bentasker/telegraf-plugins/blob/master/tor-daemon/tor-daemon.py#L483). The most likely is probably the non 250, but the capture will tell us.

Your telnet test looks like the conversation should get past that conditional, so there's likely to be some nuance we're not currently seeing.

**Comment by ditatompel** [comment]
Thank you for fast respond.
Here is my [packet capture](https://0x0.st/ouZK.txt) when I manually run the script once.

Looks like it respond with 250

**Comment by bentasker** [comment]
Thanks, yes that looks OK - just for avoidance of doubt, did the manual run still report an authentication error? If not then it might only be an issue when telegraf triggers the script (so we can narrow to focus on that), if so then it's an issue in the script somewhere.

If you edit the script around line 482 so that it becomes
```
cmd = 'AUTHENTICATE "' + AUTH + '"'
res = send_and_respond(s, cmd)
print(res)   
if len(res) < 1 or res[0] != "250 OK":
```

What do you get?

**Comment by ditatompel** [comment]
> did the manual run still report an authentication error?

Yeah, I run in manually.

> If you edit the script around line 482 ... What do you get?

It print only one empty array:
```
['']
```

What's interesting is when I try to uncomment `s.setblocking(0)` and when the script still running and hanging there, I tried to restart Tor (so it close all open connections). The script immediately return 2 arrays (the first one is `250 OK` that we expect) before broken pipe error:

```
$ python tor-daemon.py
['250 OK', '']
Traceback (most recent call last):
  File "/home/user/tor-daemon.py", line 499, in <module>
    res = send_and_respond(s, cmd)
  File "/home/user/tor-daemon.py", line 42, in send_and_respond
    a = sock.sendall(command.encode())
BrokenPipeError: [Errno 32] Broken pipe
```

is it related to `setblocking(0)` method?

**Comment by bentasker** [comment]
Hmmm interesting...

> is it related to setblocking(0) method?

Yes, it might well be - `setblocking()` tells the socket not to block if there's nothing to read (otherwise that loop of reading back will end up hanging, as you've observed).

I *think* what might be happening is that the tor daemon is being slow to respond, so, we send the auth command then try and read back. When there's nothing there (yet) we hit this
```
            if not data:
                break
```

This is a *horrible* hack but will help us prove whether that theory is correct. Could you edit the plugin around line 49 to add a sleep:
```
            time.sleep(0.5)
            data = sock.recv(1024)
            if not data:
                break
```

You'll also need to add
```
import time
```
to the top of the script.

The run will take a bit, but I suspect you'll get data back. 

If that is the issue here (which seems likely) I'll look at refactoring that function so it's less time sensitive

**Comment by ditatompel** [comment]
> This is a _horrible_ hack but will help us prove whether that theory is correct. Could you edit the plugin around line 49 to add a sleep:

It's works! Awesome! Thanks.

```
tor,controlport_connection=success,version_status=recommended,network_liveness=up,accounting_enabled=0,server_mode_enabled=0 stats_fetch_failures=0i,bytes_rx=239216i,bytes_tx=154430i,uptime=4568i,tor_version="0.4.7.7",dormant=1i,orport_reachability=1i,dirport_reachability=1i,guards_never_connected=9i,guards_down=0i,guards_up=38i,guards_unusable=3i,guards_unlisted=0i,guards_total=50i
```

0.1s sleep works on my machine, and ~1-2 seconds script execution process still quite acceptable for me.

Thanks again!

**Comment by bentasker** [comment]
Awesome thanks!

I will look at getting a proper fix in place, but glad that's got it working for you.

**Comment by bentasker** [comment]
Hey @ditatompel I've just merged some changes to the plugin, be interested in seeing whether the latest revision works for you.

**Comment by ditatompel** [comment]
> Hey @ditatompel I've just merged some changes to the plugin, be interested in seeing whether the latest revision works for you.

Hey @bentasker . I've try it at 2 different machine with different distro, it works out of the box! Also, it blazing fast, it return the metrics in an instant.

Thank you! Really great job!

**Comment by bentasker** [comment]
Awesome! Thanks for taking the time to test
