### ISSUE TITLE
soliscloud: Consider including ActivePower in output

### ISSUE THREAD

**Issue by Steve-Fry** [bentasker/telegraf-plugins#4]
Active power seems helpful to understand the instantaneous grid load rather than taking the delta in daily `gridBuyTotal` which appears to have 100W resolution only

Is it worth including? Happy to raise a PR if helpful, it's a trivial change. 

It appears we only need add the following 
``` 
        "psum" : float(inverter['psum']),
        "psumStr" : f'"{inverter["psumStr"]}"',
```
at 
https://github.com/bentasker/telegraf-plugins/blob/12694aedcc06862e38cbbc0392cc02f7fd04c258/soliscloud/soliscloud.py#L457

**Comment by bentasker** [comment]
Nice spot!

Yeah, I think it's worth adding - I've people over this weekend, but if you chuck a PR over I can review and merge
