### ISSUE TITLE
Unit change for `gridBuyToday`

### ISSUE THREAD

**Issue by Steve-Fry** [bentasker/telegraf-plugins#6]
FYI only, your assumption here holds true

https://github.com/bentasker/telegraf-plugins/blob/0bdad7494b8b0746c8c0cafc56018fb208889e3a/soliscloud/soliscloud.py#L421

![image](https://github.com/bentasker/telegraf-plugins/assets/29991066/ed868c53-7122-4f12-ba3c-6aa366d0c364)

I won't be submitting a PR for this one, as I'm pursuing another avenue that allows me to pull retrospective data from before I setup the scraper. 

Thanks for the inspiration!

**Comment by bentasker** [comment]
Thanks - that's useful to know (what a pain though...  I'll have to look at adding handling for that).

**Comment by Steve-Fry** [comment]
I'm using the `InverterDay` endpoint, and there it does seem to be consistent (kWh).

Although, if you do go down that road - mind out for `gridSellTotalEnergy` and `homeLoadTodayEnergy`, they are always zero. 

Cheers!
